import Img1 from "../assets/img/Avatars-8.png";
import Img2 from "../assets/img/Avatars-1.png";
import Img3 from "../assets/img/Avatars-2.png";
import Img4 from "../assets/img/Avatars-3.png";
import Img5 from "../assets/img/Avatars-4.png";
import Img6 from "../assets/img/Avatars-5.png";
import Img7 from "../assets/img/Avatars-6.png";
import Img8 from "../assets/img/Avatars-7.png";
import Avatar from "../assets/img/Avatars.png";
import ActionBtn from "../assets/icon/ActionBtn.svg";

export const eventFilter = [
  {
    filter: "All events",
  },
  {
    filter: "Coming soon",
  },
  {
    filter: "On going",
  },
  {
    filter: "Past events",
  },
];

// EVENT PAGE

export const eventTableHead = [
  {
    head: "Company",
  },
  {
    head: "Tickets sold",
  },
  {
    head: "Revenue",
  },
  {
    head: "Created",
  },
  {
    head: "Status",
  },
  {
    head: "",
  },
];

// ORDER PAGE

export const ordersTableHead = [
  {
    head: "Order ID",
  },
  {
    head: "Attendee",
  },
  {
    head: "Event",
  },
  {
    head: "Ticket type",
  },
  {
    head: "Ticket cost",
  },
  {
    head: "Created",
  },
  {
    head: "",
  },
];

// export const eventTableData = [];

// EVENT PAGE

export const eventTableData = [
  {
    img: Img1,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img2,
    eventTitle: "Outdoor Conveyning",
    eventCategory: "OrgNco",
    ticketSold: 10,
    ticketTotal: 150,
    revenue: "$50",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img3,
    eventTitle: "Syposium brit",
    eventCategory: "TechlifeStyle",
    ticketSold: 50,
    ticketTotal: 150,
    revenue: "$1000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img4,
    eventTitle: "Wine and Dine Abuja",
    eventCategory: "Ocenia",
    ticketSold: 100,
    ticketTotal: 150,
    revenue: "$6000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img5,
    eventTitle: "247 Worship",
    eventCategory: "koinonia",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img6,
    eventTitle: "Book and Paint Lagos",
    eventCategory: "Readers club",
    ticketSold: 150,
    ticketTotal: 150,
    revenue: "$3500",
    dateCreated: "02/01/2024",
    status: "Past event",
    action: ActionBtn,
  },
  {
    img: Img7,
    eventTitle: "The view",
    eventCategory: "NomadGroups",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img8,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img5,
    eventTitle: "247 Worship",
    eventCategory: "koinonia",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img6,
    eventTitle: "Book and Paint Lagos",
    eventCategory: "Readers club",
    ticketSold: 150,
    ticketTotal: 150,
    revenue: "$3500",
    dateCreated: "02/01/2024",
    status: "Past event",
    action: ActionBtn,
  },
  {
    img: Img7,
    eventTitle: "The view",
    eventCategory: "NomadGroups",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img8,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img1,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img2,
    eventTitle: "Outdoor Conveyning",
    eventCategory: "OrgNco",
    ticketSold: 10,
    ticketTotal: 150,
    revenue: "$50",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img3,
    eventTitle: "Syposium brit",
    eventCategory: "TechlifeStyle",
    ticketSold: 50,
    ticketTotal: 150,
    revenue: "$1000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img4,
    eventTitle: "Wine and Dine Abuja",
    eventCategory: "Ocenia",
    ticketSold: 100,
    ticketTotal: 150,
    revenue: "$6000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img1,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img2,
    eventTitle: "Outdoor Conveyning",
    eventCategory: "OrgNco",
    ticketSold: 10,
    ticketTotal: 150,
    revenue: "$50",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img3,
    eventTitle: "Syposium brit",
    eventCategory: "TechlifeStyle",
    ticketSold: 50,
    ticketTotal: 150,
    revenue: "$1000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img4,
    eventTitle: "Wine and Dine Abuja",
    eventCategory: "Ocenia",
    ticketSold: 100,
    ticketTotal: 150,
    revenue: "$6000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img5,
    eventTitle: "247 Worship",
    eventCategory: "koinonia",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img6,
    eventTitle: "Book and Paint Lagos",
    eventCategory: "Readers club",
    ticketSold: 150,
    ticketTotal: 150,
    revenue: "$3500",
    dateCreated: "02/01/2024",
    status: "Past event",
    action: ActionBtn,
  },
  {
    img: Img7,
    eventTitle: "The view",
    eventCategory: "NomadGroups",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img8,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
];

// ORDER PAGE

// export const ordersTableData = [];

export const ordersTableData = [
  {
    orderId: "NA29381",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img1,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketType: "Genin",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "OC29381",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img2,
    eventTitle: "Outdoor Conveyning",
    eventCategory: "OrgNco",
    ticketType: "Basic",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "SB39141",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img3,
    eventTitle: "Syposium brit",
    eventCategory: "TechlifeStyle",
    ticketType: "Regular",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "WD91841",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img4,
    eventTitle: "Wine and Dine Abuja",
    eventCategory: "Ocenia",
    ticketType: "Sipper",
    ticketCost: "$6",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "2W31941",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img5,
    eventTitle: "247 Worship",
    eventCategory: "koinonia",
    ticketType: "Ticket",
    ticketCost: "Free",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "BP29381",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img6,
    eventTitle: "Book and Paint Lagos",
    eventCategory: "Readers club",
    ticketType: "Ticket",
    ticketCost: "Free",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "TV49501",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img6,
    eventTitle: "The view",
    eventCategory: "NomadGroups",
    ticketType: "Regular",
    ticketCost: "$10",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "NA29385",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img6,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketType: "Genin",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "2W31941",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img5,
    eventTitle: "247 Worship",
    eventCategory: "koinonia",
    ticketType: "Ticket",
    ticketCost: "Free",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "BP29381",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img6,
    eventTitle: "Book and Paint Lagos",
    eventCategory: "Readers club",
    ticketType: "Ticket",
    ticketCost: "Free",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "TV49501",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img6,
    eventTitle: "The view",
    eventCategory: "NomadGroups",
    ticketType: "Regular",
    ticketCost: "$10",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "NA29385",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img6,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketType: "Genin",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "NA29381",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img1,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketType: "Genin",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "OC29381",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img2,
    eventTitle: "Outdoor Conveyning",
    eventCategory: "OrgNco",
    ticketType: "Basic",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "SB39141",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img3,
    eventTitle: "Syposium brit",
    eventCategory: "TechlifeStyle",
    ticketType: "Regular",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "WD91841",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img4,
    eventTitle: "Wine and Dine Abuja",
    eventCategory: "Ocenia",
    ticketType: "Sipper",
    ticketCost: "$6",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "NA29381",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img1,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketType: "Genin",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "OC29381",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img2,
    eventTitle: "Outdoor Conveyning",
    eventCategory: "OrgNco",
    ticketType: "Basic",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "SB39141",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img3,
    eventTitle: "Syposium brit",
    eventCategory: "TechlifeStyle",
    ticketType: "Regular",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "WD91841",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img4,
    eventTitle: "Wine and Dine Abuja",
    eventCategory: "Ocenia",
    ticketType: "Sipper",
    ticketCost: "$6",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "2W31941",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img5,
    eventTitle: "247 Worship",
    eventCategory: "koinonia",
    ticketType: "Ticket",
    ticketCost: "Free",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "BP29381",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img6,
    eventTitle: "Book and Paint Lagos",
    eventCategory: "Readers club",
    ticketType: "Ticket",
    ticketCost: "Free",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "TV49501",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img6,
    eventTitle: "The view",
    eventCategory: "NomadGroups",
    ticketType: "Regular",
    ticketCost: "$10",
    created: "02/01/2024",
    action: "More details",
  },
  {
    orderId: "NA29385",
    attendeeName: "Olivia Rhye",
    attendeeAvatar: Avatar,
    img: Img6,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketType: "Genin",
    ticketCost: "$1",
    created: "02/01/2024",
    action: "More details",
  },
];
