import Img1 from "../assets/img/Avatars-8.png";
import Img2 from "../assets/img/Avatars-1.png";
import Img3 from "../assets/img/Avatars-2.png";
import Img4 from "../assets/img/Avatars-3.png";
import Img5 from "../assets/img/Avatars-4.png";
import Img6 from "../assets/img/Avatars-5.png";
import Img7 from "../assets/img/Avatars-6.png";
import Img8 from "../assets/img/Avatars-7.png";
import ActionBtn from "../assets/icon/ActionBtn.svg";

export const eventFilter = [
  {
    filter: "All events",
  },
  {
    filter: "Coming soon",
  },
  {
    filter: "On going",
  },
  {
    filter: "Past events",
  },
];

export const tableHead = [
  {
    head: "Company",
  },
  {
    head: "Tickets sold",
  },
  {
    head: "Revenue",
  },
  {
    head: "Created",
  },
  {
    head: "Status",
  },
  {
    head: "",
  },
];

// export const tableData = [];

export const tableData = [
  {
    img: Img1,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img2,
    eventTitle: "Outdoor Conveyning",
    eventCategory: "OrgNco",
    ticketSold: 10,
    ticketTotal: 150,
    revenue: "$50",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img3,
    eventTitle: "Syposium brit",
    eventCategory: "TechlifeStyle",
    ticketSold: 50,
    ticketTotal: 150,
    revenue: "$1000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img4,
    eventTitle: "Wine and Dine Abuja",
    eventCategory: "Ocenia",
    ticketSold: 100,
    ticketTotal: 150,
    revenue: "$6000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img5,
    eventTitle: "247 Worship",
    eventCategory: "koinonia",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img6,
    eventTitle: "Book and Paint Lagos",
    eventCategory: "Readers club",
    ticketSold: 150,
    ticketTotal: 150,
    revenue: "$3500",
    dateCreated: "02/01/2024",
    status: "Past event",
    action: ActionBtn,
  },
  {
    img: Img7,
    eventTitle: "The view",
    eventCategory: "NomadGroups",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img8,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img5,
    eventTitle: "247 Worship",
    eventCategory: "koinonia",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img6,
    eventTitle: "Book and Paint Lagos",
    eventCategory: "Readers club",
    ticketSold: 150,
    ticketTotal: 150,
    revenue: "$3500",
    dateCreated: "02/01/2024",
    status: "Past event",
    action: ActionBtn,
  },
  {
    img: Img7,
    eventTitle: "The view",
    eventCategory: "NomadGroups",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img8,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img1,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img2,
    eventTitle: "Outdoor Conveyning",
    eventCategory: "OrgNco",
    ticketSold: 10,
    ticketTotal: 150,
    revenue: "$50",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img3,
    eventTitle: "Syposium brit",
    eventCategory: "TechlifeStyle",
    ticketSold: 50,
    ticketTotal: 150,
    revenue: "$1000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img4,
    eventTitle: "Wine and Dine Abuja",
    eventCategory: "Ocenia",
    ticketSold: 100,
    ticketTotal: 150,
    revenue: "$6000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img1,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img2,
    eventTitle: "Outdoor Conveyning",
    eventCategory: "OrgNco",
    ticketSold: 10,
    ticketTotal: 150,
    revenue: "$50",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img3,
    eventTitle: "Syposium brit",
    eventCategory: "TechlifeStyle",
    ticketSold: 50,
    ticketTotal: 150,
    revenue: "$1000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img4,
    eventTitle: "Wine and Dine Abuja",
    eventCategory: "Ocenia",
    ticketSold: 100,
    ticketTotal: 150,
    revenue: "$6000",
    dateCreated: "02/01/2024",
    status: "Ongoing",
    action: ActionBtn,
  },
  {
    img: Img5,
    eventTitle: "247 Worship",
    eventCategory: "koinonia",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img6,
    eventTitle: "Book and Paint Lagos",
    eventCategory: "Readers club",
    ticketSold: 150,
    ticketTotal: 150,
    revenue: "$3500",
    dateCreated: "02/01/2024",
    status: "Past event",
    action: ActionBtn,
  },
  {
    img: Img7,
    eventTitle: "The view",
    eventCategory: "NomadGroups",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
  {
    img: Img8,
    eventTitle: "Nigeria Anime Connect",
    eventCategory: "AnimeconNg",
    ticketSold: 0,
    ticketTotal: 150,
    revenue: "$0",
    dateCreated: "02/01/2024",
    status: "Coming soon",
    action: ActionBtn,
  },
];
