name: Preview Deployment

on:
  push:
    branches:
      - test  
  pull_request:
    types: [closed]
    branches:
      - test 

jobs:
  build_and_preview:
    permissions: write-all
    name: Web Build & Staging Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --force

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel (Preview)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}       
          vercel-org-id: ${{ secrets.TEST_VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.TEST_VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}        
          vercel-args: ""
          working-directory: ./